source $HOME/.zsh/antigen/antigen.zsh

# Aliases
source $HOME/.aliases

# Pure prompt
antigen bundle sindresorhus/pure

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen apply

# DNVM (https://github.com/aspnet/dnvm)
source dnvm.sh
